INSERT INTO CONFIG (ID, NAME, VALUE, DESC, PID, REMARK) VALUES (5, 'roles', '医师角色', '医师角色', 0, null);
INSERT INTO CONFIG (ID, NAME, VALUE, DESC, PID, REMARK) VALUES (6, 'ROLE_DOCTOR', '医师', '医师', 0, null);
INSERT INTO CONFIG (ID, NAME, VALUE, DESC, PID, REMARK) VALUES (7, 'ROLE_HEALTH_SPECIALIST', '健管师', '健管师', 0, null);
INSERT INTO CONFIG (ID, NAME, VALUE, DESC, PID, REMARK) VALUES (8, 'ROLE_NUTRITIONIST', '营养师', '营养师', 0, null);
INSERT INTO CONFIG (ID, NAME, VALUE, DESC, PID, REMARK) VALUES (9, 'ROLE_EXERCISE_SPECIALIST', '运动师', '运动师', 0, null);
INSERT INTO CONFIG (ID, NAME, VALUE, DESC, PID, REMARK) VALUES (10, 'ROLE_EMOTIONAL_COUNSELOR', '情志师', '情志师', 0, null);
INSERT INTO CONFIG (ID, NAME, VALUE, DESC, PID, REMARK) VALUES (11, 'invite_timeout', '60', '自动邀请前段超时时间', 0, null);
